substitutions:
  name: 'blauberg_s14'

external_components:
  - source:
      type: git
      url: https://github.com/Benas09/Blauberg_S14
      ref: dev
    components: [ blauberg_s14 ]

esphome:
  name: "${name}"

esp8266:
  board: d1_mini

wifi:
  ssid: 'your-wifi-ssid'
  password: 'your-wifi-password'
  power_save_mode: none

  # manual_ip:
  #   static_ip: 192.168.1.24
  #   gateway: 192.168.1.254
  #   subnet: 255.255.255.0

  ap:
    ssid: "${name}_Fallback Hotspot"
    password: "fallbackpw"

api:

ota:
  platform: esphome
  password: ""

logger:
  level: NONE

uart:
  id: uart_bus
  tx_pin: D0
  rx_pin: D1
  baud_rate: 600

blauberg_s14:
  id: blauberg_s14_controller
  uart_id: uart_bus

fan:
  name: "BlaubergS14 Fan"
  platform: blauberg_s14
  blauberg_s14_id: blauberg_s14_controller

binary_sensor:
  platform: blauberg_s14
  blauberg_s14_id: blauberg_s14_controller
  damper_status:
    name: "Summer mode"
  defrosting_status:
    name: "Defrosting in progress"
  filter_replacement_status:
    name: "Filter replacement required"

switch:
  - platform: blauberg_s14
    blauberg_s14_id: blauberg_s14_controller
    name: "Summer mode"

button:
  - platform: blauberg_s14
    blauberg_s14_id: blauberg_s14_controller
    name: "Reset filter"
